import Head from "next/head";
import { useState } from "react";
import AddEvent from "../components/AddEvent/AddEvent";
import Event from "../components/EventPost/Event";
import AddItem from "../components/AddItem/AddItem";
import styles from "../styles/Home.module.css";
import { getLatestEvents } from "../scripts/common/API";
import { border, borderRadius } from "@mui/system";
export default function Home({ posts }) {
  const [isShowingForm, showForm] = useState(false);
  let Events;
  if (posts.data) {
    Events = posts.data.map(
      ({ title, description, img_link, author, options }, i) => {
        return (
          <Event
            key={"Event" + i}
            title={title}
            description={description}
            img_link={
              img_link
                ? img_link
                : "https://lugoldedc.com/wp-content/uploads/2020/10/dvc-logo.png"
            }
            author={author}
            date={options}
          />
        );
      }
    );
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Nunito:wght@600&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main}>
        <EventsSection Events={Events} />

        <AddItem showForm={showForm} />
        {isShowingForm ? <AddEvent showForm={showForm} /> : null}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

const EventsSection = ({ Events }) => {
  return (
    <>
      <h1>Events</h1>
      <div
        style={{
          overflowX: "auto",
          width: "100vw",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          flexDirection: "row",
        }}
      >
        {Events}
      </div>
    </>
  );
};

export async function getServerSideProps() {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  const posts = await getLatestEvents(5);

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      posts: posts,
    },
  };
}
